project:
  type: website
  output-dir: docs

website:
  title: "사무엘의 수리 언어 블로그"
  navbar:
    left:
      - href: index.qmd
        text: 홈
      - href: about.qmd
        text: 소개
    right:
      - icon: github
        href: https://github.com/samuel4388
      - icon: twitter-x
        href: https://x.com/sam458755
  page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    math: mathjax
    title-block-banner: true