---
title: "지시 변수를 이렇게도 저렇게도"
lang: ko
translation-key: 250619_1
categories: [mathematics, probability]
date: 2025-06-19
---

*A First Course in Probability*, 9th edition by Sheldon Ross  
Chapter 7, Problem 7.63., p.357

확률 문제를 풀면 지시 변수\(indicator variable\)와 친해지게 된다.
재밌는 점은, 지시 변수 설정하는 방법이 한 가지만 있는 게 아니라는 것이다.
지시 변수라는 개념 자체는 간단하다.
사건이 발생하면 1이고, 사건이 발생하지 않으면 0인 변수이다.
그래서 지시 변수의 기댓값은 지시 변수가 1일 확률과 동일하다.
마치 컴퓨터의 비트와 같은 지시 변수는 잘만 활용하면 문제 풀이를 정말 용이하게 해 준다.
나는 이걸 로스 확률론 7장 63번 문제의 \(a\)를 풀면서 느꼈다.

---

**7.63.** 어떤 항아리에 공이 총 30개 들어 있는데, 그 중 10개는 빨간색이고 8개는 파란색이다.
이 항아리에서 무작위로 12개의 공을 꺼낸다.
빨간 공의 개수를 $X$, 파란 공의 개수를 $Y$라고 하자.

\(a\) 적절한 지시 변수(즉, 베르누이 확률 변수)를 정의함으로써 $\mathrm{Cov}(X, Y)$를 구하라.
$$
X_i, Y_j \text{ such that } X = \sum_{i=1}^{10} X_i, \; Y = \sum_{j=1}^{8} Y_j
$$

---

먼저 교재에 나온 지시 변수를 이용해서 \(a\)를 구해 보자.
여기서 $X_i$는 빨간 공들에 1부터 8까지 순서를 매긴 뒤에, 순서 매긴 공이 뽑혔을 때 1이 되는 지시 변수이다.
그러니까 예를 들어 $X_3 = 1$은 세 번째 빨간 공이 뽑혔다는 얘기다.
그러면 이 지시 변수들의 합인 $X$는 뽑힌 빨간 공의 개수가 된다.
$Y$에도 마찬가지의 논리가 적용된다.

그러면 공분산을 어떻게 구할 수 있을까?
공분산의 이중 선형성을 이용하면 다음과 같이 쓸 수 있다:
$$
\text{Cov}\left(X, Y\right) = \text{Cov}\left(\sum_{i=1}^{10} X_i, \sum_{j=1}^{8} Y_j\right) = \sum_{i=1}^{10} \sum_{j=1}^{8} \text{Cov}\left(X_i, Y_j\right)
$$

그러면 이제 $\mathrm{Cov}(X_i, Y_j)$를 구하면 되는데, 이는 공분산의 정의에 따라 다음과 같이 쓸 수 있다:

$$
\text{Cov}(X_i, Y_j) = E[X_i Y_j] - E[X_i] E[Y_j]
$$

$E[X_i]$를 구하는 건 쉽다.
$30$개의 공들 중에서 $12$개를 뽑는 상황이니까 전체 경우의 수는 $\binom{30}{12}$가 된다.
그런데 $i$번째 빨간 공을 구하는 경우의 수는 이미 하나를 뽑은 상황에서 나머지 $11$개의 공을 뽑는 거니까 $\binom{29}{11}$이 된다.
$E[Y_i]$에도 같은 논리가 적용돼서
$$
E[X_i] = E[Y_j] = \frac{\binom{29}{11}}{\binom{30}{12}} = \frac{\frac{29!}{18!11!}}{\frac{30!}{18!12!}} = \frac{12}{30} = \frac{2}{5}
$$

라고 쓸 수 있다.

그러면 $E[X_iY_j]$는 어떻게 구할 수 있을까?
이번에도 비슷한 논리가 적용된다.
전체 경우의 수는 같고, 이번에는 두 개가 고정된 거니까 나머지 28개의 공들 중에서 10개를 뽑으면 된다.
그러면
$$
E[X_i Y_j] = \frac{\binom{28}{10}}{\binom{30}{12}} = \frac{\frac{28!}{18!10!}}{\frac{30!}{18!12!}} = \frac{11 \cdot 12}{29 \cdot 30} = \frac{22}{145}
$$

따라서
$$
\text{Cov}(X_i, Y_j) = E[X_i Y_j] - E[X_i] E[Y_j] = \frac{22}{145} - \left(\frac{2}{5}\right)^2 = -\frac{6}{725}
$$
$$
\text{Cov}(X, Y) = 10 \cdot 8 \cdot \left(-\frac{6}{725}\right) = -\frac{96}{145}
$$

이렇게 구할 수 있다.

---

그런데 나는 사실 맨 처음에 이 문제를 접했을 때 책에 나온 지시 함수를 쓰지 않았다.
책에 나온 지시 함수로 푸는 게 조금 더 간단하긴 하지만, 나는 다른 방식으로 문제를 접근했다.
이번에는 $i$번째로 뽑은 공이 빨강이면 1인 지시 함수 $X_i$, j번째로 뽑은 공이 파랑이면 $1$인 지시 함수 $Y_j$를 생각해 보자:
$$
X_i = \begin{cases}
1, & \text{if the i-th ball is red} \\
0, & \text{otherwise}
\end{cases}, \quad
Y_j = \begin{cases}
1, & \text{if the j-th ball is blue} \\
0, & \text{otherwise}
\end{cases}
$$

그리고 $X = \sum_{i=1}^{12} X_i$, $Y = \sum_{j=1}^{12} Y_j$라고 둬 보자.
그러면 이번에는 공분산이 다음과 같이 나온다:
$$
\text{Cov}(X, Y) = \text{Cov}\left(\sum_{i=1}^{12} X_i, \sum_{j=1}^{12} Y_j\right) = \sum_{i=1}^{12} \sum_{j=1}^{12} \text{Cov}(X_i, Y_j)
$$

이번에는 이를 $i$와 $j$가 같은 경우와 다른 경우로 분리해야 한다.
왜 그럴까?
예를 들어, 다섯 번째로 뽑은 공은 빨간 공이거나 파란 공이거나 둘 다 아닐 수는 있지만, 동시에 빨갛고 파랄 수는 없기 때문이다.
그래서 이 둘을 다르게 취급해야 한다.
따라서
$$
\text{Cov}(X, Y) = \sum_{i=1}^{12} \text{Cov}(X_i, Y_i) + \sum_{i \neq j} \text{Cov}(X_i, Y_j)
$$

이렇게 쓸 수 있다.

앞서 뽑은 공들에 대한 정보가 없다는 가정 하에, 몇 번째에 뽑건 $i$번째에 뽑은 공이 파란 공일 확률은 $E[X_i] = \frac{10}{30} = \frac{1}{3}$이다.
마찬가지로 $j$번째에 뽑은 공이 빨간 공일 확률은 $E[Y_j] = \frac{8}{30} = \frac{4}{15}$이다.
$i = j$인 경우에는 $E[X_iY_j] = E[X_iY_i]$가 $0$이 될 수밖에 없다.
왜냐하면 지시 함수의 특성상 $E[X_iY_i] = P\{X_iY_i = 1\}$이어야 하는데, 앞서 말했듯이 뽑은 공이 동시에 빨갛고 파랄 수 없기 때문이다.
따라서 $i = j$인 경우
$$
\text{Cov}(X_i, Y_i) = E[X_i Y_i] - E[X_i] E[Y_i] = 0 - \frac{1}{3} \cdot \frac{4}{15} = -\frac{4}{45}
$$

가 된다.

$i ≠ j$인 경우에는 어떻게 될까?
$E[X_i]$와 $E[Y_j]$는 같고, $E[X_iY_j]$만 다르게 설정하면 된다.
$E[X_iY_j] = P\{X_iY_j = 1\}$이니까, $X_i$와 $Y_j$가 둘 다 1이 되는 상황을 생각해 보면 된다.

먼저 $i < j$인 경우를 생각해 보자.
$i$번째 뽑기에서 빨간 공이 뽑힐 확률은 $\frac{10}{30} = \frac{1}{3}$이다.
$j$번째 뽑기에서 파란 공이 뽑힐 확률은 빨간 공이 이미 하나 뽑혔으니까 $\frac{8}{30 - 1} = \frac{8}{29}$이다.
따라서 $E[X_iY_j] = \frac{1}{3} \cdot \frac{8}{29} = \frac{8}{87}$이 된다.

다음으로 $i > j$인 경우를 생각해 보자.
$j$번째 뽑기에서 파란 공이 뽑힐 확률은 $\frac{8}{30} = \frac{4}{15}$이다.
$i$번째 뽑기에서 빨간 공이 뽑힐 확률은 파란 공이 이미 하나 뽑혔으니까 $\frac{10}{30 - 1} = \frac{10}{29}$이다.
따라서 $E[X_iY_j] = \frac{4}{15} \cdot \frac{10}{29} = \frac{40}{435} = \frac{8}{87}$이 된다.

즉, $i < j$이건 $i > j$이건 $E[X_iY_j]$는 동일하다는 점을 알 수 있다.
이는 순서와 상관 없이, 빨간 공 하나, 파란 공 하나가 뽑혔다는 사실에는 변함이 없기 때문이라고 받아들일 수 있겠다.

따라서 $i ≠ j$인 경우
$$
\text{Cov}(X_i, Y_j) = E[X_i Y_j] - E[X_i] E[Y_j] = \frac{8}{87} - \frac{1}{3} \cdot \frac{4}{15} = \frac{8}{87} - \frac{4}{45} = \frac{4}{1305} \quad (i ≠ j)
$$

와 같이 구할 수 있다.

$i = j$인 경우는 12가지 경우가 있고, $i ≠ j$인 경우는 $\binom{12}{2} \cdot 2!$가지 경우가 있으므로

$$
\begin{align}
\text{Cov}(X, Y) &= \sum_{i=1}^{12} \text{Cov}(X_i, Y_i) + \sum_{i \neq j} \text{Cov}(X_i, Y_j) \\
&= 12 \cdot \left(-\frac{4}{45}\right) + \binom{12}{2} \cdot 2! \cdot \frac{4}{1305} = -\frac{96}{145}
\end{align}
$$

이와 같이 같은 결과가 나온다.